### ISSUE TITLE
Outdated Version on Crates.io

### ISSUE THREAD

**Issue by doylep** [informationsea/warp-embed#6]
Thanks for this great little crate! It would be nice if the Crates.io version had the newest revision (0.5.0). In the meantime, anyone discovering this issue can directly import from github like so:
```warp-embed = { git = "https://github.com/informationsea/warp-embed.git" }```

Cheers!
Patton

**Comment by informationsea** [comment]
Now I published version 0.5.0 to crates.io. Sorry for the inconvenience.

**Comment by doylep** [comment]
Thanks so much!
